# Generated by Django 5.0.6 on 2024-05-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Em análise', 'Em Análise'), ('Aprovado', 'Aprovado'), ('Recusado', 'Recusado'), ('Pago', 'Pago')], default='Em análise', max_length=50),
        ),
    ]
