# Generated by Django 5.0.6 on 2024-05-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
    ]
