# Generated by Django 5.0.6 on 2024-05-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_cpf_user_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=11),
        ),
    ]
