# Generated by Django 5.0.6 on 2024-05-23 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_task_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('antecipado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recebido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Em Análise', max_length=100)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.task')),
            ],
        ),
    ]
