# Generated by Django 5.0.6 on 2024-05-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(default=0, max_length=11),
        ),
    ]
