# Generated by Django 5.0.6 on 2024-05-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(default='Old Task', max_length=100),
            preserve_default=False,
        ),
    ]
