# Generated by Django 5.0.6 on 2024-05-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_transaction_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('em analise', 'Em Análise'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('recebido', 'Recebido')], default='em analise', max_length=50),
        ),
    ]
