# Generated by Django 5.0.6 on 2024-05-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Em análise', 'Em Análise'), ('Aprovado', 'Aprovado'), ('Recusado', 'Recusado'), ('Recebido', 'Recebido')], default='Em análise', max_length=50),
        ),
    ]
